### ISSUE TITLE
Adblock Test is inconsistent

### ISSUE THREAD

**Issue by ArtexJay** [d3ward/toolz#39] opened 2022-10-20 21:35 UTC
The adblock test is inconsistent or does not work well testing adguard client + adguard assistant ( not adguard adblock the extension). I have tested using the exact same rules including the rules you provided on the exact same device. And kept getting 57% on vivaldi,  Edge got 15% and then dropped to 10%.

**Comment by bongochong** [comment] 2022-11-10 21:01
As of late, I have noticed similar issues with this tool in a variety of different contexts (ad-blocking via DNS, hosts files, and even browser extensions). Results for this tool now vary wildly. Domains can be blocked across both protocols using multiple methods, and this tool will often report them as not being blocked much of the time. At the time of writing this comment, results only seem to be accurate when I run the tests on machines that don't utilize IPv6, and only use the hosts file as a means of blocking domains. This tool appears to no longer be compatible with DNS-based ad-blocking, or popular ad-blocking extensions like uBlock Origin and AdGuard.

**Comment by 0-5-0** [comment] 2022-12-11 18:38
I've noticed the same thing, I have DNSBL enabled with some lists in Unbound on OPNSense, if I run the test in Brave on my PC with uBlock Origin enabled the results will be different, lower with Brave ad blocking and uBlock Origin enabled but then higher 95% with only the lists in OPNSense/Unbound (with Brave and uBlock blocking disabled).

**Comment by picotrain77** [comment] 2023-02-04 07:59
Came here looking for a reason as to why when first loading the test page I get 94% result yet any further testing or refreshing gets me like 10% result.

**Comment by d3ward** [comment] 2023-02-04 10:33
New upcoming version will have some small improvements on detection, and more logs/details on how things work. Despite the inconsistency, the project still works with different adblock solutions, the problem is that there are thousands of scenarios from thousands of users configurations browser, platform, DNS, adblock extension etc .... it's impossible to cover all of them and I will do my best to optimise the project step by step. Closing this to have a clean list of issues for version 3.0.0 of Toolz.

**Closed by d3ward** 2023-02-04 10:33 UTC
Labels: documentation

**Comment by bongochong** [comment] 2023-03-01 16:40
I know the issue is closed, but I'm chiming in to say that the redesign is very nice, and results do appear to be more consistent. The disclaimers regarding potential inaccuracies were a smart move too. Great work.

**Comment by dim0n1** [comment] 2023-12-13 20:03
![2023-12-13 20 35 52 d3ward github io be88f8189281](https://github.com/d3ward/toolz/assets/149322426/64b78333-7239-44a0-9e08-1e5df14b7264)
![2023-12-13 20 36 50 d3ward github io 73eee5512df9](https://github.com/d3ward/toolz/assets/149322426/1a5290a2-8f97-4c74-8440-3bdf2bc4d028)
Hi, also want to ask, why same test in Vivaldi broswer gives me different results, screenshot upper, any way, after restart browser, I have better result, and after re-test result is much worse... In brave, results are consistent, in edge, same thing, first test is better then re-test? Hmm?
