### ISSUE TITLE
Problem with cache in browser

### ISSUE THREAD

**Issue by squadramunter** [d3ward/toolz#6] opened 2021-05-16 08:34 UTC
When I started the test it gives me points on what I could improve  the second test did not changed anything because it seems to cache in the browser. With incognito it did work.

I like to see if the cache is deleted when the page loads again

**Comment by squadramunter** [comment] 2021-05-16 08:40
I am running this on latest Google Chrome

**Comment by d3ward** [comment] 2021-07-18 11:31
Do you still have that bug ? Im taking a look these days and can't reproduce the bug

**Comment by d3ward** [comment] 2023-02-04 10:22
Closing as this is related to the used browser

**Closed by d3ward** 2023-02-04 10:22 UTC
Labels: bug
